//
// PLEASE DO NOT EDIT!!
// This file was generated by scripts/codegen.py, go edit that instead!
//

namespace Sandbox.Sdf;

partial class Sdf3DMeshWriter
{
	partial void AddTriangles( in Sdf3DArrayData data, int x, int y, int z )
	{
		var aRaw = data[x + 0, y + 0, z + 0];
		var bRaw = data[x + 1, y + 0, z + 0];
		var cRaw = data[x + 0, y + 1, z + 0];
		var dRaw = data[x + 1, y + 1, z + 0];

		var eRaw = data[x + 0, y + 0, z + 1];
		var fRaw = data[x + 1, y + 0, z + 1];
		var gRaw = data[x + 0, y + 1, z + 1];
		var hRaw = data[x + 1, y + 1, z + 1];

		var a = aRaw < 128 ? CubeConfiguration.A : 0;
		var b = bRaw < 128 ? CubeConfiguration.B : 0;
		var c = cRaw < 128 ? CubeConfiguration.C : 0;
		var d = dRaw < 128 ? CubeConfiguration.D : 0;

		var e = eRaw < 128 ? CubeConfiguration.E : 0;
		var f = fRaw < 128 ? CubeConfiguration.F : 0;
		var g = gRaw < 128 ? CubeConfiguration.G : 0;
		var h = hRaw < 128 ? CubeConfiguration.H : 0;

		var config = a | b | c | d | e | f | g | h;

		switch ( config )
		{
			case CubeConfiguration.None:
				return;

			case CubeConfiguration.A:
				AddTriangle( x, y, z, CubeVertex.AC, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AE );
				return;

			case CubeConfiguration.C:
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.CG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C:
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.AE );
				return;

			case CubeConfiguration.D:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.D:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AE );
				return;

			case CubeConfiguration.C | CubeConfiguration.D:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.AE );
				return;

			case CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.EG, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.AC, CubeVertex.EG, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.AC, CubeVertex.EF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AE, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.CG, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.EG, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.AE, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.CG, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.EG, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.EF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.EF );
				return;

			case CubeConfiguration.D | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.EG, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AC, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AE, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.EF );
				return;

			case CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.CG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.D | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.BD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.BF );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.BD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.BF );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.EG );
				return;

			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.EG );
				return;

			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.EG );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.BD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.BF );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.EG );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.EG );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.EG );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.EG );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.EG );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.GH, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.EG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.AE, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.AB, CubeVertex.AC );
				return;

			case CubeConfiguration.B | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.GH, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AE );
				return;

			case CubeConfiguration.C | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.EG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.EG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AE );
				return;

			case CubeConfiguration.D | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AE );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AE );
				return;

			case CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.GH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.EF, CubeVertex.AE );
				return;

			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.GH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.EF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.AB, CubeVertex.AC );
				return;

			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AE, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.GH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.AE, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.GH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.CD, CubeVertex.EF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EF );
				return;

			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.AB, CubeVertex.AE );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.DH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.EF );
				return;

			case CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.EG, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.EG, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.EG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AC, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.AB, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.EF, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AC, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.GH );
				return;

			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CG, CubeVertex.GH );
				return;

			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AE, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AC, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.AB, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.GH );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.BD, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.CD, CubeVertex.GH );
				return;

			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.AB, CubeVertex.AE );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				AddTriangle( x, y, z, CubeVertex.FH, CubeVertex.DH, CubeVertex.GH );
				return;

			case CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.AC, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.BF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.FH );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.BF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.FH );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.GH );
				return;

			case CubeConfiguration.C | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.CD );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.AE );
				return;

			case CubeConfiguration.D | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AE );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.AE );
				return;

			case CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.GH );
				return;

			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.GH );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AC, CubeVertex.EG );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AE, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AC, CubeVertex.EG );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AC );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.GH );
				return;

			case CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.GH );
				return;

			case CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AC, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AC, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AC, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.GH );
				return;

			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.GH );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.GH );
				return;

			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.GH );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.GH, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AC, CubeVertex.EG );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AE, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.AC, CubeVertex.EG );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AC );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.GH, CubeVertex.CG, CubeVertex.EG );
				return;

			case CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.CG );
				return;

			case CubeConfiguration.A | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CG );
				return;

			case CubeConfiguration.B | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.BF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.FH );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.CG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CG );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AE );
				return;

			case CubeConfiguration.C | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.CD );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AE );
				return;

			case CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CG, CubeVertex.CD );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.CD, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AE );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.EG, CubeVertex.AE );
				return;

			case CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.CG );
				return;

			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CG );
				return;

			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.CG );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CG );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.CD );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );
				return;

			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.AB, CubeVertex.AE );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.FH, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BF, CubeVertex.FH, CubeVertex.EF );
				return;

			case CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.CG );
				return;

			case CubeConfiguration.A | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CG );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.CG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CG );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.EG, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AC, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.AB, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.EF, CubeVertex.EG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.EF );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EF, CubeVertex.EG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.EG, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AC, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AB, CubeVertex.EF );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.EG, CubeVertex.AE, CubeVertex.EF );
				return;

			case CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.CG );
				return;

			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CG );
				return;

			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.CG );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CG );
				return;

			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AE, CubeVertex.AC );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AC, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BF, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.AB, CubeVertex.CD );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );

				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.DH, CubeVertex.BD, CubeVertex.CD );
				return;

			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.CG );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.CG, CubeVertex.CD );
				return;

			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );

				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AB );
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.AB, CubeVertex.AE );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.CG, CubeVertex.CD, CubeVertex.AC );
				return;

			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AE );
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.AE, CubeVertex.AC );
				return;

			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.BD, CubeVertex.BF, CubeVertex.AB );
				return;

			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				AddTriangle( x, y, z, CubeVertex.AE, CubeVertex.AC, CubeVertex.AB );
				return;

			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;

		}
	}
}
